name: native_webview
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 1.4.0
homepage: https://github.com/hisaichi5518/native_webview

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hisaichi5518.native_webview
        pluginClass: NativeWebviewPlugin
      ios:
        pluginClass: NativeWebviewPlugin
