name: native_webview
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 0.28.0
homepage: https://github.com/hisaichi5518/native_webview

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  plugin:
    platforms:
      android:
        package: com.hisaichi5518.native_webview
        pluginClass: NativeWebviewPlugin
      ios:
        pluginClass: NativeWebviewPlugin
